#?filename=deploy-kubernetes.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cao-gateway
spec:
  selector:
    matchLabels:
      app: cao-gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: cao-gateway
    spec:
      containers:
        - name: cao-gateway
          image: stefv013/cao-gateway
          imagePullPolicy: Always
          ports:
            - name: listen-port
              containerPort: 8080
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              cpu: 1
              memory: 256Mi
---
kind: Service
apiVersion: v1
metadata:
  name: cao-gateway
spec:
  selector:
    app: cao-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer