#?filename=deploy-kubernetes.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: policeservice
spec:
  selector:
    matchLabels:
      app: policeservice
  replicas: 1
  template:
    metadata:
      labels:
        app: policeservice
    spec:
      containers:
        - name: policeservice
          image: stefv013/policeservice
          imagePullPolicy: Always
          ports:
            - name: listen-port
              containerPort: 6789
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              cpu: 1
              memory: 512Mi
---
kind: Service
apiVersion: v1
metadata:
  name: hotel-service
spec:
  selector:
    app: hotel-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6789
  type: LoadBalancer