#?filename=deploy-kubernetes.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-service
spec:
  selector:
    matchLabels:
      app: hotel-service
  replicas: 1
  template:
    metadata:
      labels:
        app: hotel-service
    spec:
      containers:
        - name: hotel-service
          image: stefv013/hotelservice
          imagePullPolicy: Always
          ports:
            - name: listen-port
              containerPort: 1001
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              cpu: 1
              memory: 512Mi
---
kind: Service
apiVersion: v1
metadata:
  name: hotel-service
spec:
  selector:
    app: hotel-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1001
  type: LoadBalancer