#?filename=deploy-kubernetes.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-rental-service
spec:
  selector:
    matchLabels:
      app: car-rental-service
  replicas: 1
  template:
    metadata:
      labels:
        app: car-rental-service
    spec:
      containers:
        - name: car-rental-service
          image: stefv013/carrentalservice
          imagePullPolicy: Always
          ports:
            - name: listen-port
              containerPort: 1000
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              cpu: 1
              memory: 512Mi
---
kind: Service
apiVersion: v1
metadata:
  name: car-rental-service
spec:
  selector:
    app: acar-rental-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1000
  type: LoadBalancer