#?filename=deploy-kubernetes.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: carrentalservice
spec:
  selector:
    matchLabels:
      app: carrentalservice
  replicas: 1
  template:
    metadata:
      labels:
        app: carrentalservice
    spec:
      containers:
        - name: carrentalservice
          image: stefv013/carrentalservice
          imagePullPolicy: Always
          ports:
            - name: listen-port
              containerPort: 1000
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              cpu: 1
              memory: 256Mi
---
kind: Service
apiVersion: v1
metadata:
  name: carrentalservice
spec:
  selector:
    app: carrentalservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1000
  type: LoadBalancer